/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ASYMMBREITWIGNER
#define ASYMMBREITWIGNER

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class AsymmBreitWigner : public RooAbsPdf {
public:
  AsymmBreitWigner() {} ; 
  AsymmBreitWigner(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mu,
	      RooAbsReal& _gamma,
	      RooAbsReal& _n,
	      RooAbsReal& _alpha);
  AsymmBreitWigner(const AsymmBreitWigner& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new AsymmBreitWigner(*this,newname); }
  inline virtual ~AsymmBreitWigner() { }

protected:

  RooRealProxy x ;
  RooRealProxy mu ;
  RooRealProxy gamma ;
  RooRealProxy n ;
  RooRealProxy alpha ;
  
  Double_t evaluate() const ;

private:

  ClassDef(AsymmBreitWigner,1) // Your description goes here...
};
 
#endif
